name: $(Date:yyyy-MM-dd)-rev$(Rev:r)
trigger:
  batch: true
  branches:
    include:
    - master
    - rel/*
pr:
- '*'
resources:
  repositories:
  - repository: templates
    type:       github
    name:       thnetii/azure-pipelines
    endpoint:   thnetii
jobs:
- template: templates/dotnetcore/azure-pipelines.yml@templates
  parameters:
    checkout:
    - checkout:   self
      submodules: true
    presteps:
    - task: UseDotNet@2
      displayName:  Use .NET Core Runtime version 2.0.9
      inputs:
        packageType:  runtime
        version:      2.0.9
    - task: UseDotNet@2
      displayName:  Use .NET Core SDK version 3.x
      inputs:
        version:    3.x
